package applicationcontroller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import applicationmain.Main;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class FormularioFornecedoresController {
	@FXML
	private TextField textFNome;
	@FXML
	private TextField textFCnpj;
	@FXML
	private TextField textFEndereco;
	@FXML
	private Button voltarMenu;
	@FXML
	private Label labelNovoFornecedor;
	@FXML
	private Label labelEditarFornecedor;
	@FXML
	private Button novoFornecedor;
	@FXML
	private Button editarFornecedor;

	// Event Listener on Button[#voltarMenu].onAction
	@FXML
	public void acaoVoltarMenu(ActionEvent event) {
		
		Main.mudarPrimeiraTela("GerenciamentoFornecedores");
		
	}
	// Event Listener on Button[#novoFornecedor].onAction
	@FXML
	public void acaoAddFornecedor(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#editarFornecedor].onAction
	@FXML
	public void acaoEditFornecedor(ActionEvent event) {
		// TODO Autogenerated
	}
}
