package applicationcontroller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class FormularioPratosController implements Initializable {
	@FXML
	private TextField textFNome;
	@FXML
	private TextField textFPreco;
	@FXML
	private TextField textFCategoria;
	@FXML
	private Button voltarMenu;
	@FXML
	private Label labelNovoPrato;
	@FXML
	private Label labelEditarPrato;
	@FXML
	private Button novoPrato;
	@FXML
	private Button editarPrato;

	// Event Listener on Button[#voltarMenu].onAction
	@FXML
	public void acaoVoltarMenu(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#novoPrato].onAction
	@FXML
	public void acaoAddPrato(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#editarPrato].onAction
	@FXML
	public void acaoEditPrato(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
}
