package applicationcontroller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import applicationmain.Main;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.DatePicker;

public class FormularioProdutosController {
	@FXML
	private TextField textFNome;
	@FXML
	private TextField textFPreco;
	@FXML
	private TextField textFQtd;
	@FXML
	private DatePicker datePickerProduto;
	@FXML
	private Button voltarMenu;
	@FXML
	private Label labelNovoProduto;
	@FXML
	private Label labelEditarProduto;
	@FXML
	private Button novoProduto;
	@FXML
	private Button editarProduto;

	// Event Listener on Button[#voltarMenu].onAction
	@FXML
	public void acaoVoltarMenu(ActionEvent event) {
		
		Main.mudarPrimeiraTela("GerenciamentoProdutos");
		
	}
	// Event Listener on Button[#novoProduto].onAction
	@FXML
	public void acaoAddProduto(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#editarProduto].onAction
	@FXML
	public void acaoEditProduto(ActionEvent event) {
		// TODO Autogenerated
	}
}
