package applicationcontroller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class FormularioFornecedoresController implements Initializable{
	@FXML
	private TextField textFNome;
	@FXML
	private TextField textFCnpj;
	@FXML
	private TextField textFEndereco;
	@FXML
	private Button voltarMenu;
	@FXML
	private Label labelNovoFornecedor;
	@FXML
	private Label labelEditarFornecedor;
	@FXML
	private Button novoFornecedor;
	@FXML
	private Button editarFornecedor;
	
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		// TODO Auto-generated method stub
		
	}
	// Event Listener on Button[#voltarMenu].onAction
	@FXML
	public void acaoVoltarMenu(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#novoFornecedor].onAction
	@FXML
	public void acaoAddFornecedor(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#editarFornecedor].onAction
	@FXML
	public void acaoEditFornecedor(ActionEvent event) {
		// TODO Autogenerated
	}
	
}
