package applicationcontroller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.event.ActionEvent;
import javafx.scene.input.MouseEvent;

public class PaginaPrincipalController {
	@FXML
	private Button bGFornecedores;
	@FXML
	private Button bGProdutos;
	@FXML
	private Button bGPratos;
	@FXML
	private Button bGVendas;
	@FXML
	private Button bGUsuarios;
	@FXML
	private Button bGClientes;
	@FXML
	private Button bGSair;

	// Event Listener on Button[#bGFornecedores].onAction
	@FXML
	public void acessDaoFornecedores(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bGFornecedores].onMouseEntered
	@FXML
	public void alterarCorBotaoEntered(MouseEvent event) {
		
	
//		Button botaoPress = (Button)event.getSource();
//		botaoPress.setTextFill(Color.RED);
		
	}
	// Event Listener on Button[#bGFornecedores].onMouseExited
	@FXML
	public void alterarCorBotaoExited(MouseEvent event) {
		
//		Button botaoPress = (Button)event.getSource();
//		botaoPress.setTextFill(Color.BLACK);
		
	}
	// Event Listener on Button[#bGProdutos].onAction
	@FXML
	public void acessDaoProdutos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bGPratos].onAction
	@FXML
	public void acessDaoPratos(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bGVendas].onAction
	@FXML
	public void acessDaoVendas(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bGUsuarios].onAction
	@FXML
	public void acessDaoUsuarios(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bGClientes].onAction
	@FXML
	public void acessDaoClientes(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#bGSair].onAction
	@FXML
	public void acessSaida(ActionEvent event) {
		// TODO Autogenerated
	}
}
